/**
 * Tokens and principals: the one place a plaintext token is turned into an
 * identity, a self-service mint creates a principal and its token, and a
 * token is revoked. Rows are decoded through `SqlSchema` here and nowhere
 * else in the capability, so a client type change lands in one module.
 *
 * Only a token's hash is stored: the plaintext is generated by the caller,
 * shown once, and never recoverable from the store.
 */
import * as Clock from "effect/Clock";
import * as Context from "effect/Context";
import * as Duration from "effect/Duration";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Option from "effect/Option";
import * as Redacted from "effect/Redacted";
import * as Schema from "effect/Schema";
import * as SqlClient from "effect/unstable/sql/SqlClient";
import type { SqlError } from "effect/unstable/sql/SqlError";
import * as SqlSchema from "effect/unstable/sql/SqlSchema";
import { Identity } from "@patchy/api";
import { newInternalId, sha256 } from "@patchy/core";
import * as AuthConfig from "./AuthConfig.js";

/**
 * The principal and token named by fixed ids rather than generated ones,
 * seeded from `PATCHY_BOOTSTRAP_API_TOKEN`. Their legacy scopes grant no
 * platform powers. Every other principal is a self-service mint found by lookup.
 */
export const BOOTSTRAP_PRINCIPAL_ID = "acct_bootstrap";
export const BOOTSTRAP_API_TOKEN_ID = "tok_bootstrap";

/**
 * How far back a mint still counts against its source address: a rolling
 * day ending now, not a calendar day. A calendar day resets at one instant
 * every client can predict, which turns "five a day" into "ten across
 * midnight" for anyone willing to wait; a rolling window has no such seam,
 * and needs no timezone.
 */
export const MINT_QUOTA_WINDOW = Duration.days(1);

/** The mint quota is a database count, so it survives a restart; the ceiling is configuration. */
export class MintQuotaExceeded extends Schema.TaggedError<MintQuotaExceeded>()(
  "MintQuotaExceeded",
  {
    sourceIp: Schema.NullOr(Schema.String),
    quota: Schema.Int
  }
) {
  override get message() {
    return `Mint quota reached: ${this.quota} self-service tokens per address per 24 hours.`;
  }
}

export interface MintInput {
  /** The mint's source address, or `null` when the request has no usable one. */
  readonly sourceIp: string | null;
  /** The quota ceiling this mint is held to. */
  readonly quota: number;
  /** The internal name for both the new principal and its token. */
  readonly name: string;
  /** The plaintext; only `sha256(token)` is stored. */
  readonly token: string;
}

export interface Minted {
  readonly accountId: string;
  readonly apiTokenId: string;
}

/**
 * The outcome of a revocation. Revoked is a state, never a deletion: the row
 * survives with its mint provenance, and `revokedAt` is when the freeze began.
 */
export interface Revocation {
  readonly id: string;
  readonly accountId: string;
  readonly name: string;
  readonly revokedAt: string;
  /** True when the token was already revoked and this call changed nothing. */
  readonly alreadyRevoked: boolean;
}

export class Tokens extends Context.Service<
  Tokens,
  {
    /** The identity a plaintext token resolves to; `None` for an unknown or revoked one. */
    readonly authenticate: (token: string) => Effect.Effect<Option.Option<Identity>, SqlError>;
    /**
     * A self-service mint: a fresh principal, the one token that controls it,
     * and the mint record, together or not at all — a principal with no token
     * owns patches nobody can reach, and a token with no mint record is one
     * the quota cannot see. The quota is counted inside the same transaction.
     */
    readonly mint: (input: MintInput) => Effect.Effect<Minted, MintQuotaExceeded | SqlError>;
    /** Idempotent: revoking twice answers the same, with the first `revokedAt` intact. */
    readonly revoke: (apiTokenId: string) => Effect.Effect<Option.Option<Revocation>, SqlError>;
  }
>()("@patchy/auth/Tokens") {}

class RecentMints extends Schema.Class<RecentMints>("RecentMints")({ mints: Schema.Int }) {}

class RevocationRow extends Schema.Class<RevocationRow>("RevocationRow")({
  id: Schema.String,
  accountId: Schema.String,
  name: Schema.String,
  // Today's client hands back a Date; when it becomes epoch ms only this line moves.
  revokedAt: Schema.Date,
  alreadyRevoked: Schema.Boolean
}) {}

/** A `SchemaError` on a row is a bug in the query or the schema, never a caller's fault. */
const dieOnSchemaError = { SchemaError: Effect.die } as const;

export const make = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient;

  const bootstrap = yield* AuthConfig.bootstrapApiToken;
  if (Option.isSome(bootstrap)) yield* seedBootstrap(sql, Redacted.value(bootstrap.value));

  const findIdentity = SqlSchema.findOneOption({
    Request: Schema.String,
    Result: Identity,
    execute: (tokenHash) => sql`
      SELECT t.account_id AS "accountId", a.name AS "accountName",
             t.id AS "apiTokenId", t.name AS "apiTokenName", t.scopes
      FROM api_tokens t JOIN accounts a ON a.id = t.account_id
      WHERE t.token_hash = ${tokenHash} AND t.revoked_at IS NULL`
  });

  // `IS NOT DISTINCT FROM` so a null address matches the null rows rather than
  // matching nothing: unattributable mints share one bucket.
  const countRecentMints = SqlSchema.findOne({
    Request: Schema.Struct({ sourceIp: Schema.NullOr(Schema.String), sinceMillis: Schema.Number }),
    Result: RecentMints,
    execute: ({ sinceMillis, sourceIp }) => sql`
      SELECT count(*)::int AS mints FROM token_mints
      WHERE source_ip IS NOT DISTINCT FROM ${sourceIp}
        AND created_at >= to_timestamp(${sinceMillis / 1_000})`
  });

  // Read the row under a lock, stamp it only if it is not already stamped, and
  // report the state it was in beforehand — one statement, so two concurrent
  // revocations of the same token cannot both claim the first.
  const revokeRow = SqlSchema.findOneOption({
    Request: Schema.String,
    Result: RevocationRow,
    execute: (apiTokenId) => sql`
      WITH prior AS (
        SELECT id, account_id, name, revoked_at FROM api_tokens WHERE id = ${apiTokenId} FOR UPDATE
      ),
      revoked AS (
        UPDATE api_tokens SET revoked_at = now() FROM prior
        WHERE api_tokens.id = prior.id AND prior.revoked_at IS NULL
        RETURNING api_tokens.revoked_at
      )
      SELECT prior.id, prior.account_id AS "accountId", prior.name,
             COALESCE((SELECT revoked_at FROM revoked), prior.revoked_at) AS "revokedAt",
             prior.revoked_at IS NOT NULL AS "alreadyRevoked"
      FROM prior`
  });

  const authenticate = Effect.fn("Tokens.authenticate")((token: string) =>
    findIdentity(sha256(token)).pipe(Effect.catchTags(dieOnSchemaError))
  );

  const mint = Effect.fn("Tokens.mint")((input: MintInput) =>
    sql.withTransaction(
      Effect.gen(function* () {
        // The quota counts these rows on the Effect clock, so a test can wind it.
        const now = yield* Clock.currentTimeMillis;
        const { mints } = yield* countRecentMints({
          sourceIp: input.sourceIp,
          sinceMillis: now - Duration.toMillis(MINT_QUOTA_WINDOW)
          // `count(*)` always answers one row; no row is a bug, not a state.
        }).pipe(Effect.catchTags({ NoSuchElementError: Effect.die }));
        if (mints >= input.quota) {
          return yield* new MintQuotaExceeded({ sourceIp: input.sourceIp, quota: input.quota });
        }

        const accountId = newInternalId("acct");
        const apiTokenId = newInternalId("tok");
        yield* sql`INSERT INTO accounts (id, name) VALUES (${accountId}, ${input.name})`;
        yield* sql`
          INSERT INTO api_tokens (id, account_id, name, token_hash, scopes)
          VALUES (${apiTokenId}, ${accountId}, ${input.name}, ${sha256(input.token)}, '["upload"]'::jsonb)`;
        yield* sql`
          INSERT INTO token_mints (id, account_id, api_token_id, source_ip, created_at)
          VALUES (${newInternalId("mint")}, ${accountId}, ${apiTokenId}, ${input.sourceIp}, to_timestamp(${now / 1_000}))`;
        return { accountId, apiTokenId } satisfies Minted;
      }).pipe(Effect.catchTags(dieOnSchemaError))
    )
  );

  const revoke = Effect.fn("Tokens.revoke")((apiTokenId: string) =>
    revokeRow(apiTokenId).pipe(
      Effect.catchTags(dieOnSchemaError),
      Effect.map(
        Option.map((row): Revocation => ({
          id: row.id,
          accountId: row.accountId,
          name: row.name,
          revokedAt: row.revokedAt.toISOString(),
          alreadyRevoked: row.alreadyRevoked
        }))
      )
    )
  );

  return Tokens.of({ authenticate, mint, revoke });
});

/** Idempotent: re-running restores the bootstrap token if it was rotated or revoked. */
const seedBootstrap = (sql: SqlClient.SqlClient, token: string) =>
  Effect.gen(function* () {
    yield* sql`
      INSERT INTO accounts (id, name) VALUES (${BOOTSTRAP_PRINCIPAL_ID}, 'Bootstrap Account')
      ON CONFLICT (id) DO NOTHING`;
    yield* sql`
      INSERT INTO api_tokens (id, account_id, name, token_hash, scopes)
      VALUES (${BOOTSTRAP_API_TOKEN_ID}, ${BOOTSTRAP_PRINCIPAL_ID}, 'Bootstrap API Token', ${sha256(token)}, '["admin", "upload"]'::jsonb)
      ON CONFLICT (id) DO UPDATE
        SET token_hash = EXCLUDED.token_hash, scopes = EXCLUDED.scopes, revoked_at = NULL`;
  });

/** Over the Postgres client; seeds the bootstrap principal when a token is configured. */
export const layer = Layer.effect(Tokens, make);
