/**
 * PROTOTYPE (#176). The tree `patchy init --tier 1` lays down, as strings.
 * Everything an agent needs in its first ten minutes is here or one command
 * away: the config it edits, the client it calls, the context file that
 * names the company and the dev identity, and the skill that says how the
 * loop works. Two kinds of file: laid down once and owned by the repo
 * (config, index.html, main.ts), and regenerated by `patchy refresh`
 * (the context file, the generated directory, the skill).
 */

export interface Context {
  readonly name: string;
  readonly tier: 0 | 1;
  readonly instanceUrl: string;
  readonly company: { readonly id: string; readonly handle: string; readonly name: string };
  readonly user: { readonly id: string; readonly email: string; readonly name: string };
  readonly machine: { readonly id: string; readonly name: string };
  readonly patchId: string | null;
  /** Where `@patchy/sdk` resolves from in this prototype; a version in the real thing. */
  readonly sdkSpec: string;
  readonly refreshedAt: string;
}

// --- owned by the repo, written once -----------------------------------------

export const patchConfig = (
  tier: 0 | 1
) => `import { defineConfig, files, t, table } from "@patchy/sdk";

/**
 * What this patch is and what it owns. The tier says where its code runs
 * (1: in the viewer's browser). Tables and file stores defined here are
 * provisioned for the patch on publish and exist only for it. Adding a
 * table or an optional column is a publish away; renaming, retyping or
 * dropping is refused, so pick names you can live with.
 */
export default defineConfig({
  tier: ${tier},
  tables: {
    notes: table({
      title: t.text(),
      body: t.text().optional(),
      pinned: t.boolean().default(false),
      createdAt: t.timestamp().default("now")
    })
  },
  files: {
    attachments: files()
  }
});
`;

export const patchJson = (patchId: string | null) => JSON.stringify({ patchId }, null, 2) + "\n";

export const packageJson = (name: string, sdkSpec: string) =>
  JSON.stringify(
    {
      name,
      private: true,
      type: "module",
      scripts: {
        dev: "patchy dev",
        publish: "patchy publish",
        refresh: "patchy refresh",
        typecheck: "tsc --noEmit"
      },
      dependencies: { "@patchy/sdk": sdkSpec },
      devDependencies: {
        typescript: "^5.9.0",
        vite: "^7.0.0",
        "vite-plugin-singlefile": "^2.3.0"
      }
    },
    null,
    2
  ) + "\n";

export const viteConfig = `import { defineConfig } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

/**
 * Written by \`patchy init\`. \`patchy dev\` starts this with the local
 * runtime's address in PATCHY_RUNTIME_URL; every /_patchy call the SDK
 * makes is proxied there. The build is one HTML file, which is what
 * \`patchy publish\` uploads.
 */
export default defineConfig({
  plugins: [viteSingleFile()],
  server: {
    proxy: {
      "/_patchy": process.env.PATCHY_RUNTIME_URL ?? "http://127.0.0.1:1"
    }
  }
});
`;

export const tsconfig =
  JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "Bundler",
        lib: ["ES2022", "DOM", "DOM.Iterable"],
        strict: true,
        noEmit: true,
        skipLibCheck: true,
        isolatedModules: true,
        types: ["vite/client"]
      },
      include: ["src", "patchy", "patchy.config.ts", "vite.config.ts"]
    },
    null,
    2
  ) + "\n";

/** pnpm 10+ refuses to run esbuild's postinstall without this; without it Vite cannot start. */
export const pnpmWorkspace = `allowBuilds:
  esbuild: true
`;

export const gitignore = `node_modules
dist
# Local dev data: PGlite and the file store. Recreatable; never commit.
.patchy/
`;

export const indexHtml = (name: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name}</title>
    <style>
      body { font: 15px/1.5 system-ui, sans-serif; max-width: 40rem; margin: 3rem auto; padding: 0 1rem; color: #1a1a1a; }
      form { display: grid; gap: .5rem; margin: 1.5rem 0; }
      input, textarea, button { font: inherit; padding: .5rem .6rem; }
      li { margin: .5rem 0; }
      small { color: #666; }
    </style>
  </head>
  <body>
    <h1>${name}</h1>
    <p id="me"><small>Loading who you are…</small></p>
    <form id="new-note">
      <input name="title" placeholder="Title" required />
      <textarea name="body" placeholder="Body (optional)" rows="2"></textarea>
      <button>Add note</button>
    </form>
    <ul id="notes"></ul>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`;

export const mainTs = `import { patchy } from "../patchy/_generated/client";

// The starter: who the viewer is, one query, one insert. Everything goes
// through \`patchy\`; there is no other way to reach data, in dev or deployed.

const me = await patchy.me();
document.querySelector("#me")!.textContent = \`Signed in as \${me.user.name} at \${me.company.name}\`;

const list = document.querySelector<HTMLUListElement>("#notes")!;

const render = async () => {
  const notes = await patchy.tables.notes.list({ limit: 50 });
  list.replaceChildren(
    ...notes.map((note) => {
      const item = document.createElement("li");
      item.innerHTML = \`<strong></strong> <small></small><br /><span></span>\`;
      item.querySelector("strong")!.textContent = note.title;
      item.querySelector("small")!.textContent = new Date(note.createdAt).toLocaleString();
      item.querySelector("span")!.textContent = note.body ?? "";
      return item;
    })
  );
};

document.querySelector<HTMLFormElement>("#new-note")!.addEventListener("submit", async (event) => {
  event.preventDefault();
  const form = event.currentTarget as HTMLFormElement;
  const data = new FormData(form);
  await patchy.tables.notes.insert({
    title: String(data.get("title")),
    body: String(data.get("body") || "") || null
  });
  form.reset();
  await render();
});

await render();
`;

// --- regenerated by `patchy refresh` -------------------------------------------

export const generatedClient = `// Generated by \`patchy refresh\`. Do not edit; edit patchy.config.ts instead.
import { createClient } from "@patchy/sdk";
import config from "../../patchy.config";

/** The typed client for everything this patch defines in patchy.config.ts. */
export const patchy = createClient(config);
export type Config = typeof config;
`;

export const generatedContext = (context: Context) =>
  JSON.stringify(
    {
      generatedBy: "patchy refresh",
      refreshedAt: context.refreshedAt,
      instanceUrl: context.instanceUrl,
      company: context.company,
      devIdentity: { user: context.user, machine: context.machine },
      patchId: context.patchId,
      declarations: {}
    },
    null,
    2
  ) + "\n";

export const agentsMd = (context: Context) => `# ${context.name}

This is a **Patchy patch repo**: one deployable tool for the company **${context.company.name}** (\`${context.company.handle}\`), built for tier ${context.tier} (code runs in the viewer's browser and acts as them).

Before changing anything, read \`.agents/skills/patchy-sdk/SKILL.md\`. It is short and it is the whole workflow.

## Identity

- Instance: ${context.instanceUrl}
- Dev identity: **${context.user.name}** (${context.user.email}), through the machine key **${context.machine.name}**. \`patchy dev\` runs the local runtime as this user; nothing here reaches production data.
- Patch id: ${context.patchId ?? "none yet — the first \`patchy publish\` creates the patch and writes it to \`patchy.json\`"}

## Commands

| Command | What it does |
| --- | --- |
| \`patchy dev\` | Local runtime (PGlite + a file store under \`.patchy/\`) plus Vite, at one URL. Provisions whatever \`patchy.config.ts\` defines. |
| \`patchy publish\` | Builds, checks the tier, provisions new tables/columns/stores in the company database, uploads a version. |
| \`patchy refresh\` | Re-fetches this file, \`patchy/_generated/\` and the skill from the instance. Run it after login changes or when the SDK moves. |

Last refreshed ${context.refreshedAt}.
`;

export const claudeMd = `@AGENTS.md
`;

export const skillMd = `---
name: patchy-sdk
description: Build and publish this patch with the Patchy SDK — define tables and file stores in patchy.config.ts, use the typed client, run the local dev loop, publish. Read before editing anything in a patch repo.
---

# Building a patch

A patch is a file tree that publishes as one thing at one address. This repo is one patch. The only way patch code reaches data is the typed client in \`patchy/_generated/client.ts\`; it speaks to Patchy, which performs every call as the viewer, within their permissions. There is no database URL, no credential and no other API for patch code, in dev or deployed.

## The loop

1. Define what the patch owns in \`patchy.config.ts\`: tables (\`table({...})\` with \`t.text()\`, \`t.integer()\`, \`t.boolean()\`, \`t.timestamp()\`, \`t.json()\`, each \`.optional()\` or \`.default(...)\`) and file stores (\`files()\`). Every table gets an \`id\` for free. Do not add an \`id\` column.
2. Run \`patchy dev\`. It provisions the config into a local PGlite database under \`.patchy/\` and serves the app with Vite. Rows in dev are local and synthetic; delete \`.patchy/\` to start over.
3. Write UI in \`index.html\` and \`src/\`. Import \`patchy\` from \`../patchy/_generated/client\` and call \`patchy.tables.<name>.insert/list/get/delete\` and \`patchy.files.<name>.put/get/list/delete\`. Types come from the config; if the editor shows a table missing, you have not defined it.
4. Run \`patchy publish\`. The first publish creates the patch and writes its id to \`patchy.json\`; commit that file. Later publishes add versions.

## Rules the cloud enforces

- **Schema changes are additive.** A publish may add tables, add optional or defaulted columns, and add file stores. It refuses renames, type changes, drops and new required columns without a default. Old versions people still have open keep working because nothing they use can vanish.
- **The tier is checked against the tree.** A tier 0 patch may not ship script; a tier 1 patch may not ship server code. Declare the tier the tree needs.
- **Permissions are Patchy's.** Whoever can open the patch can read and write all of its tables and files. Do not build access rules in the page; they would run in the viewer's browser and bind nobody.
- **Never edit \`patchy/_generated/\`.** \`patchy refresh\` rewrites it. Change \`patchy.config.ts\` and the types follow.
- **Never hardcode an instance URL, a token, or a database connection.** The client finds Patchy by itself; the CLI holds the login.

## Files

| Path | Yours to edit? | What it is |
| --- | --- | --- |
| \`patchy.config.ts\` | yes | Tier, tables, file stores. The source of truth for what the patch owns. |
| \`index.html\`, \`src/\` | yes | The app. Vite serves and bundles it. |
| \`patchy.json\` | no | The patch id, written by the first publish. Commit it. |
| \`patchy/_generated/\` | no | The typed client and the context the instance served. |
| \`AGENTS.md\` | no | Company, dev identity, commands. Refreshed with \`patchy refresh\`. |
| \`.patchy/\` | no | Local dev data. Gitignored, recreatable. |

## Adding a file upload

\`\`\`ts
const input = document.querySelector<HTMLInputElement>("input[type=file]")!;
const file = input.files![0];
await patchy.files.attachments.put(file.name, file, file.type);
const blob = await patchy.files.attachments.get(file.name);
img.src = URL.createObjectURL(blob);
\`\`\`
`;
