// @effect-diagnostics nodeBuiltinImport:off
// Real files exercise command ownership across an author's later saves.
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, expect, it } from "vitest";
import { ManagedProject } from "./ManagedProject.js";

const directories: string[] = [];
const originalPackage = '{\n  "devDependencies": { "patchy": "old-release" }\n}\n';
const project = async () => {
  const root = await mkdtemp(join(tmpdir(), "patchy-managed-"));
  directories.push(root);
  await writeFile(join(root, "package.json"), originalPackage);
  await writeFile(join(root, "patchy.config.ts"), "original config");
  return root;
};
const bytes = async (directory: string): Promise<Record<string, Buffer>> => {
  const result: Record<string, Buffer> = {};
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      for (const [name, contents] of Object.entries(await bytes(join(directory, entry.name))))
        result[`${entry.name}/${name}`] = contents;
    } else result[entry.name] = await readFile(join(directory, entry.name));
  }
  return result;
};
afterEach(async () => {
  await Promise.all(
    directories.splice(0).map((root) => rm(root, { recursive: true, force: true }))
  );
});

it("leaves an author's config save alone when plain refresh fails", async () => {
  const root = await project();
  const transaction = await ManagedProject.begin(root);
  await writeFile(join(root, "patchy.config.ts"), "author's saved config");
  await transaction.finish(false);
  expect(await readFile(join(root, "patchy.config.ts"), "utf8")).toBe("author's saved config");
});

it("undoes only its package pin while retaining later scripts and formatting", async () => {
  const root = await project();
  const transaction = await ManagedProject.begin(root);
  await transaction.setPin("old-release", "new-release");
  const authored =
    '{\n\t"scripts" : { "build": "my-build" },\n  "devDependencies": { "patchy": "new-release" }\n}\n';
  await writeFile(join(root, "package.json"), authored);
  await transaction.finish(false);
  expect(await readFile(join(root, "package.json"), "utf8")).toBe(
    authored.replace("new-release", "old-release")
  );
});

it("preserves a malformed author package saved after its pin edit", async () => {
  const root = await project();
  const transaction = await ManagedProject.begin(root);
  await transaction.setPin("old-release", "new-release");
  const authored = '{ "devDependencies": { "patchy": "author-release" }';
  await writeFile(join(root, "package.json"), authored);
  await transaction.finish(false);
  expect(await readFile(join(root, "package.json"), "utf8")).toBe(authored);
});

it("restores every generated byte after activation fails without enrolling config", async () => {
  const root = await project();
  const generated = join(root, "patchy/_generated");
  await mkdir(join(generated, "nested"), { recursive: true });
  await writeFile(join(generated, "old.ts"), "old generated\r\n");
  await writeFile(join(generated, "nested/index.json"), '{"old":true}\n');
  const before = await bytes(generated);
  const transaction = await ManagedProject.begin(root);
  await transaction.activate(
    [{ path: "patchy/_generated/client.ts", contents: "new generated\n" }],
    "{}"
  );
  await writeFile(join(root, "patchy.config.ts"), "author's saved config");
  await transaction.finish(false);
  expect(await bytes(generated)).toEqual(before);
  expect(await readFile(join(root, "patchy.config.ts"), "utf8")).toBe("author's saved config");
});

it("refuses a staged uses edit after an author save, keeping config and generated bytes", async () => {
  const root = await project();
  const generated = join(root, "patchy/_generated");
  await mkdir(generated, { recursive: true });
  await writeFile(join(generated, "client.ts"), "old generated");
  const before = await bytes(generated);
  const transaction = await ManagedProject.begin(root);
  await writeFile(join(root, "patchy.config.ts"), "author's saved config");
  try {
    await expect(
      transaction.activate(
        [{ path: "patchy/_generated/client.ts", contents: "new generated" }],
        "{}",
        [],
        { before: "original config", after: "config with added uses" }
      )
    ).rejects.toThrow();
  } finally {
    await transaction.finish(false);
  }
  expect(await readFile(join(root, "patchy.config.ts"), "utf8")).toBe("author's saved config");
  expect(await bytes(generated)).toEqual(before);
});
