// PROTOTYPE for #314: the tier 2 server bundle and the import check.
//
// `server/*.ts` is bundled into one ESM module with a generated guest entry that dispatches
// `<module>.<export>` to the handler, hands it a context whose table operations go over the
// loopback callback stub, and answers `__describe` with the handlers' descriptors. The build
// uses the repo's installed Vite (8, rolldown) in library mode: no second toolchain in the
// scaffold. The import check is a `resolveId` plugin applied to both bundles, so an off-list
// bare import is refused when the module graph is built, before any optimisation could erase
// it, and the refusal names the importing file.
//
// Discovery loads the exact bundle bytes in a throwaway workerd and reads the descriptors the
// invocation path would see; the manifest carries them, and the server re-derives and compares.
// @effect-diagnostics nodeBuiltinImport:off -- resolves the builder's installed Vite and workerd, never a second bundled toolchain.
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
import * as path from "node:path";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import type { Handlers } from "@patchy/api";
import { sha256 } from "@patchy/core";
import { Engine, workerdBinary } from "@patchy/execution";
import type * as Vite from "vite";
import { LocalError } from "./CliError.js";

/** The release's allowlist per graph; the server list is `patchy` only. */
const allowlist = {
  client: ["preact", "@preact/signals"],
  server: []
} as const;

const isBare = (source: string) =>
  !source.startsWith(".") &&
  !source.startsWith("/") &&
  !source.startsWith("\0") &&
  !source.startsWith("virtual:") &&
  !source.startsWith("data:") &&
  !/^[a-zA-Z]:[\\/]/.test(source);

const allowed = (graph: keyof typeof allowlist, source: string) =>
  source === "patchy" ||
  source.startsWith("patchy/") ||
  // Vite injects its module-preload polyfill into the HTML entry; it is not patch code.
  source.startsWith("vite/") ||
  allowlist[graph].some((name) => source === name || source.startsWith(`${name}/`));

export class ImportRefused extends Error {
  override readonly name = "ImportRefused";
  constructor(
    readonly source: string,
    readonly importer: string,
    graph: keyof typeof allowlist
  ) {
    super(
      `Import of "${source}" in ${importer} is not available on this release. ` +
        `Bare imports in ${graph === "client" ? "src/" : "server/"} resolve only to patchy${
          allowlist[graph].length ? ` and ${allowlist[graph].join(", ")}` : ""
        }; copy it into \`src/\` or ask Patchy for the capability.`
    );
  }
}

/** Refuses off-list bare imports from patch code; dependencies' own imports are theirs. */
export const importCheck = (root: string, graph: keyof typeof allowlist): Vite.Plugin => ({
  name: "patchy-import-check",
  enforce: "pre",
  resolveId(source, importer) {
    if (importer === undefined || !isBare(source) || allowed(graph, source)) return null;
    const relative = path.relative(root, importer.split("?")[0] ?? importer);
    if (relative.startsWith("..") || relative.split(path.sep).includes("node_modules")) return null;
    throw new ImportRefused(source, relative, graph);
  }
});

export const loadVite = (root: string) =>
  Effect.tryPromise({
    try: async () => {
      const require = createRequire(path.join(root, "package.json"));
      const module: typeof Vite = await import(pathToFileURL(require.resolve("vite")).href);
      return module;
    },
    catch: (cause) =>
      new LocalError({
        message: "Could not load the repo's installed Vite. Run `pnpm install`.",
        cause
      })
  });

/** The guest entry: dispatch, the context over the callback stub, and `__describe`. */
const guestEntry = (modules: readonly string[]) => `// @ts-nocheck
// Generated by patchy for the server bundle; do not edit.
${modules.map((name, index) => `import * as m${index} from "../server/${name}.ts";`).join("\n")}
import { HandlerError, isHandler } from "patchy/server";
const modules = { ${modules.map((name, index) => `${JSON.stringify(name)}: m${index}`).join(", ")} };
const json = (value) => new Response(JSON.stringify(value), { headers: { "content-type": "application/json" } });
const describe = () => {
  const handlers = {};
  for (const [module, exports] of Object.entries(modules)) {
    for (const [name, value] of Object.entries(exports)) {
      if (!isHandler(value)) return { ok: false, error: "not_a_handler", export: module + "." + name };
      const descriptor = JSON.parse(JSON.stringify({ kind: value.kind, args: value.args, result: value.result, errors: value.errors }));
      if (descriptor.errors.length === 0) delete descriptor.errors;
      handlers[module + "." + name] = descriptor;
    }
  }
  return { ok: true, handlers };
};
const tableClient = (call, table) => ({
  get: (id) => call("tables.get", { table, id }),
  getMany: (ids) => call("tables.getMany", { table, ids }),
  list: (options = {}) => call("tables.list", { ...options, table }),
  insert: (row) => call("tables.insert", { table, row }),
  insertMany: (rows) => call("tables.insertMany", { table, rows }),
  update: (id, patch) => call("tables.update", { table, id, patch }),
  delete: (id) => call("tables.delete", { table, id })
});
export default {
  async fetch(request, env, ctx) {
    const body = await request.json();
    if (body.handler === "__ping") return json({ ok: true });
    if (body.handler === "__describe") return json(describe());
    const dot = String(body.handler).indexOf(".");
    const exports = modules[String(body.handler).slice(0, dot)];
    const definition = exports === undefined ? undefined : exports[String(body.handler).slice(dot + 1)];
    if (!isHandler(definition)) return json({ ok: false, error: "no_such_handler" });
    const log = [];
    const callbacks = ctx.props.callbacks;
    const call = async (op, args) => {
      const reply = await callbacks.call(op, args);
      if (reply.ok) return reply.result;
      throw Object.assign(new Error(reply.message ?? "callback refused: " + reply.code), {
        patchyRefusal: { code: reply.code, message: reply.message, details: reply.details }
      });
    };
    const tables = new Proxy({}, { get: (_target, table) => (typeof table === "string" ? tableClient(call, table) : undefined) });
    const context = {
      viewer: body.viewer,
      tables,
      log: (message, details) => {
        if (log.length < 100) log.push(details === undefined ? { message: String(message) } : { message: String(message), details });
      }
    };
    try {
      const result = await definition.handler(context, body.args ?? {});
      return json({ ok: true, result: result === undefined ? null : result, log });
    } catch (error) {
      if (error instanceof HandlerError) return json({ ok: false, error: "handler", code: error.code, details: error.details, log });
      if (error !== null && typeof error === "object" && "patchyRefusal" in error) return json({ ok: false, error: "refused", ...error.patchyRefusal, log });
      return json({ ok: false, error: "failed", message: error instanceof Error ? error.message : String(error), stack: error instanceof Error ? error.stack : undefined, log });
    }
  }
};
`;

const failed = (message: string) => (cause: unknown) =>
  cause instanceof ImportRefused
    ? new LocalError({ message: cause.message, code: "import_refused", cause })
    : new LocalError({ message, cause });

/** The `server/*.ts` module names, one level deep; nothing else is a handler module. */
export const serverModules = Effect.fn("serverModules")(function* (root: string) {
  const fs = yield* FileSystem.FileSystem;
  const directory = path.join(root, "server");
  const exists = yield* fs.exists(directory).pipe(Effect.orElseSucceed(() => false));
  if (!exists) return [];
  const entries = yield* fs
    .readDirectory(directory)
    .pipe(
      Effect.mapError((cause) => new LocalError({ message: "Could not read server/.", cause }))
    );
  return entries
    .filter((entry) => /^[a-z][a-zA-Z0-9]{0,62}\.ts$/.test(entry))
    .map((entry) => entry.slice(0, -3))
    .sort();
});

/** The generated guest entry under `.patchy/`, imported by both the publish and dev builds. */
export const writeServerEntry = Effect.fn("writeServerEntry")(function* (
  root: string,
  modules: readonly string[]
) {
  const fs = yield* FileSystem.FileSystem;
  const entry = path.join(root, ".patchy", "server-entry.ts");
  yield* fs.makeDirectory(path.dirname(entry), { recursive: true }).pipe(
    Effect.andThen(fs.writeFileString(entry, guestEntry(modules))),
    Effect.mapError(
      (cause) => new LocalError({ message: "Could not write the server entry.", cause })
    )
  );
  return entry;
});

/** One ESM module for the engine; the import check runs on this graph. */
export const buildServerBundle = Effect.fn("buildServerBundle")(function* (root: string) {
  const modules = yield* serverModules(root);
  if (modules.length === 0)
    return yield* new LocalError({
      message: "A tier 2 repo needs at least one server/<module>.ts exporting a handler."
    });
  const vite = yield* loadVite(root);
  const entry = yield* writeServerEntry(root, modules);
  const output = yield* Effect.tryPromise({
    try: () =>
      vite.build({
        root,
        configFile: false,
        logLevel: "silent",
        clearScreen: false,
        plugins: [importCheck(root, "server")],
        build: {
          lib: { entry, formats: ["es"], fileName: () => "server.js" },
          write: false,
          minify: false,
          sourcemap: false,
          target: "es2022",
          rolldownOptions: { output: { codeSplitting: false } }
        }
      }),
    catch: failed("Server bundle build failed. Fix the errors in server/ before publishing.")
  });
  const outputs = Array.isArray(output) ? output : [output];
  const chunks = outputs.flatMap((item) =>
    "output" in item ? item.output.filter((chunk) => chunk.type === "chunk") : []
  );
  if (chunks.length !== 1)
    return yield* new LocalError({
      message: `The server bundle must be one module; Vite emitted ${chunks.length}.`
    });
  const bundle = chunks[0]!.code;
  return { modules, bundle, digest: sha256(bundle) };
});

/** Loads the exact bytes in a throwaway workerd and reads the descriptors invocation will see. */
export const discoverHandlers = Effect.fn("discoverHandlers")(function* (
  root: string,
  bundle: string
): Effect.fn.Return<Handlers, LocalError> {
  const binary = yield* workerdBinary(path.join(root, "package.json")).pipe(
    Effect.mapError((cause) => new LocalError({ message: cause.message, cause }))
  );
  return yield* Engine.inspectBundle(binary, bundle).pipe(
    Effect.mapError(
      (cause) =>
        new LocalError({
          message:
            cause._tag === "InspectionFailed"
              ? `Could not derive the handler map: ${cause.reason}`
              : cause.message,
          code: "invalid_manifest",
          cause
        })
    )
  );
});
