import { registry, type LimitDefinition, type LimitId } from "./registry.js";

const entries = Object.entries(registry) as [LimitId, LimitDefinition][];

function table(rows: readonly [LimitId, LimitDefinition][]): string {
  return [
    "<!-- prettier-ignore -->",
    "| Limit id | Kind | Default | Unit | Scope | Measures | Refusal | Company override | Configuration |",
    "| --- | --- | ---: | --- | --- | --- | --- | --- | --- |",
    ...rows.map(
      ([id, limit]) =>
        `| \`${id}\` | ${limit.kind} | ${limit.default} | ${limit.unit} | ${limit.scope} | ${limit.measure} | ${limit.refusal === null ? "None" : `\`${limit.refusal}\``} | ${limit.overridable ? "Yes" : "No"} | ${limit.configuration ?? (limit.kind === "contract" ? "release" : "deployment")} |`
    )
  ].join("\n");
}

/** The contract ticket embeds this generated section in patchy-server. */
export function renderServerSkillLimits(): string {
  return [
    "## Limits",
    "",
    "Contract limits are fixed for this release. Operating limits below are current defaults, not capacity promises; a company may have overrides. Handle the listed refusals. Admission is counted per host replica.",
    "",
    `A frame may have ${registry["frame.outstanding"].default} requests outstanding, but company connections and action admission can refuse earlier. Callbacks and subscription re-runs do not spend the per-viewer call rate. Calls never automatically retry busy; subscriptions back off.`,
    "",
    "PGlite dev has one connection. It does not reproduce production connection contention, serialization conflicts or containment. A watchdog kill is not proof of CPU abuse. Use bounded batches for long actions.",
    "",
    table(entries.filter(([id]) => !id.startsWith("rate."))),
    ""
  ].join("\n");
}

export function renderLimitsMarkdown(): string {
  return [
    "# Limits",
    "",
    "Generated from `packages/limits/src/registry.ts`. Run `pnpm --filter @patchy/limits render-docs` after changing the registry. Do not edit this file by hand.",
    "",
    "Contract limits are constants in the release. Production deployment configuration cannot change them; tests can inject explicit contract values. Operating limits have deployment defaults and, where marked, per-company overrides. This table includes bounds for the tier 2 build; registering a bound does not enable the feature that enforces it.",
    "",
    "## Configuration and overrides",
    "",
    "`OperatingLimits` loads `PATCHY_LIMITS_JSON`, a JSON object mapping managed operating limit ids to positive finite numbers. Unknown ids, contract ids and rows marked `legacy` are refused. An omitted id uses its registry default. The deployment revision is a SHA-256 digest of the sorted, resolved managed operating values, including release defaults. It changes automatically when an effective value changes; there is no operator-maintained revision variable.",
    "",
    "Tier 2 enforcers read `OperatingLimits.get` as they are implemented. Existing control-plane rates and the host backend budget retain their named environment variables or fixed defaults. Their rows are marked `legacy` in the registry and are refused by both the JSON configuration and the override controller, including reads, rather than reported with a value that might not be enforced. Existing runtime and frame contract bounds read the registry and are not deployment-configurable.",
    "",
    "Controller code uses `OperatingLimits.setOverride` and `removeOverride`, never row edits. Each write records the company, limit id, actor, timestamp, old and new effective values, old and new override values, and configuration revision. Removing an override restores the current deployment value. `get` returns the effective value with `{ deploymentRevision, overrideRevision }`; `history` returns the changes. The durable company revision advances atomically with each change and survives removal. The deployment revision distinguishes changes to the deployment defaults, so a measurement identifies both settings in force.",
    "",
    "Host-wide limits cannot have company overrides. Per-company admission counters remain per host replica. A limit refusal identifies `code`, `scope`, `limitId` and the effective `value`, with `retryAfter` in seconds only where retrying is safe.",
    "",
    "## Registry",
    "",
    table(entries),
    "",
    "## Generation for the server skill",
    "",
    "`renderServerSkillLimits()` from `@patchy/limits/render` generates the limits section for the `patchy-server` skill. `pnpm --filter @patchy/limits render-docs --skill` prints that section. The normal `render-docs` command updates this document, the checked-in snapshot at `packages/limits/generated/server-skill-limits.md`, and the marked section in `packages/sdk/skills/patchy-server/SKILL.md`; tests fail if any output is stale.",
    "",
    "## Units and settlement",
    "",
    "All byte limits, including process RSS and Fargate memory, are recorded in bytes. Defaults use binary multiples where the decision names KiB, MiB or GiB; Fargate memory defaults are converted from MiB. Deadlines, idle windows and retention periods are milliseconds; retry delays on the wire are seconds. A scope of viewer may be further bound to a patch or document as the measure column states.",
    "",
    "At a caller deadline, effects are fenced and cancellation begins. It does not promise rollback by that instant. An unresolved mutation commit is `unknown_outcome`, not `handler_timeout`; settlement destroys an unresolved connection after its cleanup bound. Query and mutation cancellation use their caller deadlines. No per-invocation CPU or memory guarantee is claimed.",
    "",
    "## Runaway code and residency",
    "",
    `The execution supervisor probes and samples process CPU/RSS every ${registry["execution.probe.interval"].default} ms. It kills a process still running at its caller deadline plus ${registry["tier2.query.kill"].default - registry["tier2.query.deadline"].default} ms, after ${registry["execution.stall"].default} ms without a successful probe, or at ${registry["execution.process.rss"].default} bytes RSS. Every in-flight attempt is reported to the host for commit-outcome classification; a kill alone never establishes rollback.`,
    "",
    `Residency permits ${registry["execution.residency.processes"].default} loaded version processes and ${registry["execution.residency.bytes"].default} bytes aggregate RSS, including the supervisor, bundles, reports and overlapping versions. Enforcement continues while processes are loaded. Memory pressure evicts the largest idle process first; otherwise the oldest idle process goes first. If none is idle, new work receives busy. Processes idle for ${registry["execution.process.idle"].default} ms are reaped.`,
    "",
    "The local executor applies the aggregate ceiling only to supervised workerd processes. Its PGlite, fixture and Vite host does not consume that budget. The dedicated fleet supervisor retains host-inclusive accounting; both modes keep the same process count, per-process RSS and watchdog enforcement.",
    "",
    "Process reports retain CPU seconds and peak RSS sampled before the operating system removes the process record. The host receives and acknowledges these reports over the private management channel. CPU is attributed to the patch version, not individual invocations. The company task is the security boundary; process separation provides availability isolation. Local execution uses the same watchdog but proves neither Fargate containment nor per-invocation CPU or memory isolation.",
    "",
    "## Company tasks and the fleet",
    "",
    `The controller targets max(${registry["execution.pool.spares"].default}, company wakes per millisecond over ${registry["execution.pool.wakeWindow"].default} ms times measured cold-start milliseconds), rounded up. Spares, bound tasks and draining tasks share the ${registry["execution.fleet.budget"].default}-task fleet budget. One replica holds the ${registry["execution.housekeeping.lease"].default} ms housekeeping lease; passes run every ${registry["execution.housekeeping.interval"].default} ms.`,
    "",
    `A first open waits at most ${registry["execution.pool.wait"].default} ms for a binding. The shell holds calls within its normal byte and outstanding-call bounds, shows the starting cover after two seconds and refuses held calls busy on start_failed, without replay. It retries binding with backoff while open. Release follows ${registry["execution.company.idle"].default} ms with no connected tier 2 documents and no admitted work, including nested calls, retries and cleanup. The controller fences admissions before stopping a task; released tasks never become spares.`,
    "",
    `Across host replicas and versions, ${registry["execution.breaker.kills"].default} watchdog kills within ${registry["execution.breaker.window"].default} ms pause the patch for ${registry["execution.breaker.pause"].default} ms. Admission returns patch_paused with retryAfter. A new publish clears the pause; rollback and sharing changes do not. The breaker is off in the no-pool development executor.`,
    "",
    "Binding history meters company bound seconds through the provider's observed stop time, including reconciliation after a lost task. Supervisor process reports are stored before acknowledgement. These records do not depend on best-effort wide-event delivery.",
    ""
  ].join("\n");
}
