import { registry, type LimitDefinition, type LimitId } from "./registry.js";

const entries = Object.entries(registry) as [LimitId, LimitDefinition][];

function table(rows: readonly [LimitId, LimitDefinition][]): string {
  return [
    "<!-- prettier-ignore -->",
    "| Limit id | Kind | Default | Unit | Scope | Measures | Refusal | Company override | Configuration |",
    "| --- | --- | ---: | --- | --- | --- | --- | --- | --- |",
    ...rows.map(
      ([id, limit]) =>
        `| \`${id}\` | ${limit.kind} | ${limit.default} | ${limit.unit} | ${limit.scope} | ${limit.measure} | ${limit.refusal === null ? "None" : `\`${limit.refusal}\``} | ${limit.overridable ? "Yes" : "No"} | ${limit.configuration ?? (limit.kind === "contract" ? "release" : "deployment")} |`
    )
  ].join("\n");
}

/** The contract ticket embeds this generated section in patchy-server. */
export function renderServerSkillLimits(): string {
  return [
    "## Limits",
    "",
    "Contract limits are fixed for this release. Operating limits below are current defaults, not capacity promises; a company may have overrides. Handle the listed refusals. Admission is counted per host replica.",
    "",
    `A frame may have ${registry["frame.outstanding"].default} requests outstanding, but company connections and action admission can refuse earlier. Callbacks and subscription re-runs do not spend the per-viewer call rate. Calls never automatically retry busy; subscriptions back off.`,
    "",
    "PGlite dev has one connection. It does not reproduce production connection contention, serialization conflicts or containment. A watchdog kill is not proof of CPU abuse. Use bounded batches for long actions.",
    "",
    table(entries.filter(([id]) => !id.startsWith("rate."))),
    ""
  ].join("\n");
}

export function renderLimitsMarkdown(): string {
  return [
    "# Limits",
    "",
    "Generated from `packages/limits/src/registry.ts`. Run `pnpm --filter @patchy/limits render-docs` after changing the registry. Do not edit this file by hand.",
    "",
    "Contract limits are constants in the release. Production deployment configuration cannot change them; tests can inject explicit contract values. Operating limits have deployment defaults and, where marked, per-company overrides. This table includes bounds for the tier 2 build; registering a bound does not enable the feature that enforces it.",
    "",
    "## Configuration and overrides",
    "",
    "`OperatingLimits` loads `PATCHY_LIMITS_JSON`, a JSON object mapping managed operating limit ids to positive finite numbers. Unknown ids, contract ids and rows marked `legacy` are refused. An omitted id uses its registry default. The deployment revision is a SHA-256 digest of the sorted, resolved managed operating values, including release defaults. It changes automatically when an effective value changes; there is no operator-maintained revision variable.",
    "",
    "Tier 2 enforcers read `OperatingLimits.get` as they are implemented. Existing control-plane rates and the host backend budget retain their named environment variables or fixed defaults. Their rows are marked `legacy` in the registry and are refused by both the JSON configuration and the override controller, including reads, rather than reported with a value that might not be enforced. Existing runtime and frame contract bounds read the registry and are not deployment-configurable.",
    "",
    "Controller code uses `OperatingLimits.setOverride` and `removeOverride`, never row edits. Each write records the company, limit id, actor, timestamp, old and new effective values, old and new override values, and configuration revision. Removing an override restores the current deployment value. `get` returns the effective value with `{ deploymentRevision, overrideRevision }`; `history` returns the changes. The durable company revision advances atomically with each change and survives removal. The deployment revision distinguishes changes to the deployment defaults, so a measurement identifies both settings in force.",
    "",
    "Host-wide limits cannot have company overrides. Per-company admission counters remain per host replica. A limit refusal identifies `code`, `scope`, `limitId` and the effective `value`, with `retryAfter` in seconds only where retrying is safe.",
    "",
    "## Registry",
    "",
    table(entries),
    "",
    "## Generation for the server skill",
    "",
    "`renderServerSkillLimits()` from `@patchy/limits/render` generates the limits section for the `patchy-server` skill. `pnpm --filter @patchy/limits render-docs --skill` prints that section. The normal `render-docs` command updates this document, the checked-in snapshot at `packages/limits/generated/server-skill-limits.md`, and the marked section in `packages/sdk/skills/patchy-server/SKILL.md`; tests fail if any output is stale.",
    "",
    "## Units and settlement",
    "",
    "All byte limits, including process RSS and Fargate memory, are recorded in bytes. Defaults use binary multiples where the decision names KiB, MiB or GiB; Fargate memory defaults are converted from MiB. Deadlines, idle windows and retention periods are milliseconds; retry delays on the wire are seconds. A scope of viewer may be further bound to a patch or document as the measure column states.",
    "",
    "At a caller deadline, effects are fenced and cancellation begins. It does not promise rollback by that instant. An unresolved mutation commit is `unknown_outcome`, not `handler_timeout`; settlement destroys an unresolved connection after its cleanup bound. Query and mutation cancellation use their caller deadlines. No per-invocation CPU or memory guarantee is claimed.",
    ""
  ].join("\n");
}
